version: "3.7"

services: 
    kot:
        container_name: king-of-time-app
        build:
            context: ./docker
            dockerfile: Dockerfile
        working_dir: /var/app 
        volumes:
            - ./src:/var/app
        entrypoint: ["ruby", "kingoftime.rb"]
        env_file: .env